blank_issues_enabled: false
contact_links:
  - name: PaperMod Discussions
    url: https://github.com/adityatelange/hugo-PaperMod/discussions
    about: Please ask and answer questions/doubts here, do not open an issue for questions.

title: "Zhenyuan's Blog"

paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45


minify:
  disableXML: true
  minifyOutput: true

params:
  homeInfoParams:
    Title: Hi there 👋 
    Content: Weocome to my blog.I 'm a software development engineer working in Bytedance. I love reading and writing in my spare time. I want to share what I read and what I think in my blog.
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Zhenyuan
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

menu:
  main:
    - identifier: archives #注意对齐空格
      name: archives
      url: /archives/
      weight: 10
    - identifier: search
      name: search
      url: /search/
      weight: 30
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    # - identifier: posts
    #   name: posts 
    #   url: /post/
    #   weight: 20
    - identifier: digital garden
      name: digital garden
      url: https://qiuzhenyuan.vercel.app
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
